on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test custom action
    steps:
    - name: Test Action 
      id: test_custom_action
      uses: Gaurang033/actionDemo@v0.4
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "Hello World"
